class CreateMembers < ActiveRecord::Migration
  def change
    create_table :members do |t|
      t.string :first_name,       :limit => 50, :null => false
      t.string :last_name,        :limit => 50, :null => false
      t.string :prefix,           :limit => 10, :null => false
      t.string :mobile_phone,     :limit => 20, :null => false
      t.string :email_id,         :limit => 50, :null => false
      t.boolean :is_owner,        :default => true,  :null => false
      t.boolean :live_here,       :default => true,  :null => false
      t.boolean :email_bills,     :default => true,  :null => false
      t.boolean :sms_bills,       :default => true,  :null => false
      t.boolean :sms_receipt,     :default => true,  :null => false
      t.boolean :is_mc_member,    :default => false,  :null => false
      t.integer :mem_id

      t.timestamps
    end
       
    Member.create(:mobile_phone => "0000000000", :first_name => "Name", :last_name => "No", :email_id => "noname@chsdesk.com", :prefix => "No")
    Member.create(:mobile_phone => "9843707178", :first_name => "SAVIO", :last_name => "Shah", :email_id => "saviowilld@lv.com", :prefix => "Mr.")
    Member.create(:mobile_phone => "9543707178", :first_name => "Dinesh", :last_name => "Shah", :email_id => "Dinesh@lv.net", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9343707178", :first_name => "Gurpreet", :last_name => "Shah", :email_id => "onyewuo@chsdesk.org", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9443707178", :first_name => "PRMOD", :last_name => "Shah", :email_id => "sarrm@chsdesk.org", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9911736445", :first_name => "SUDHAKAR", :last_name => "PATEL", :email_id => "SINGHl@chsdesk.org", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9811736445", :first_name => "Nitin", :last_name => "Witsel", :email_id => "witsela@chsdesk.us", :prefix => "Mr.")
    Member.create(:mobile_phone => "9711736445", :first_name => "ABUZAR", :last_name => "Defour", :email_id => "defours@chsdesk.us", :prefix => "Mr.")
    Member.create(:mobile_phone => "9611736445", :first_name => "Reginal", :last_name => "Patel", :email_id => "BHOSALEux@chsdesk.us", :prefix => "Mr.")
    Member.create(:mobile_phone => "9111736445", :first_name => "Nirmala", :last_name => "GUPTA", :email_id => "jova@chsdesk.us", :prefix => "Ms.")
    Member.create(:mobile_phone => "9711736445", :first_name => "Laxminarayan", :last_name => "De Camargo", :email_id => "decamar@chsdesk.us", :prefix => "Ms.")
    Member.create(:mobile_phone => "9437049875", :first_name => "SWAPNIL", :last_name => "GUPTA", :email_id => "mbokani@chsdesk.us", :prefix => "Ms.")
    Member.create(:mobile_phone => "9837849875", :first_name => "Benjamin", :last_name => "Ghosh", :email_id => "nicaise@chsdesk.aus", :prefix => "Mr.")
    Member.create(:mobile_phone => "9937849875", :first_name => "Sinan", :last_name => "Ghosh", :email_id => "NIKAM@chsdesk.aus", :prefix => "Ms.")
    Member.create(:mobile_phone => "9537849875", :first_name => "YURAJ", :last_name => "KUKRETI", :email_id => "YURAJb@chsdesk.in", :prefix => "Ms.")
    Member.create(:mobile_phone => "9637849875", :first_name => "KISHOR", :last_name => "KUKRETI", :email_id => "KADAM@chsdesk.in", :prefix => "Ms.")
    Member.create(:mobile_phone => "9467849875", :first_name => "Jitendra", :last_name => "DAS", :email_id => "carce@chsdesk.in", :prefix => "Mr.")
    Member.create(:mobile_phone => "9487849875", :first_name => "Chintanbhai", :last_name => "Mangala", :email_id => "manga@chsdesk.in", :prefix => "Mr.")
    Member.create(:mobile_phone => "9439849875", :first_name => "JIGNESH", :last_name => "PUROHIT", :email_id => "jmiku@chsdesk.com", :prefix => "Shri")
    Member.create(:mobile_phone => "9432849875", :first_name => "CHELLADURAI", :last_name => "PATIL", :email_id => "maestro@chsdesk.net", :prefix => "Mr.")
    Member.create(:mobile_phone => "9437049875", :first_name => "Valluuripalli", :last_name => "Patel", :email_id => "bolo@chsdesk.net", :prefix => "Mr.")
    Member.create(:mobile_phone => "9437249875", :first_name => "Joaquim", :last_name => "Patel", :email_id => "vishal.vashish@rediffmail.us", :prefix => "Mr.")
    Member.create(:mobile_phone => "9437866875", :first_name => "Pierre", :last_name => "AMBANI", :email_id => "tf@chsdesk.net", :prefix => "Ms.")
    Member.create(:mobile_phone => "9437822875", :first_name => "Tarique", :last_name => "Khan", :email_id => "vmalhot@exports.com", :prefix => "Ms.")
    Member.create(:mobile_phone => "9437449875", :first_name => "Jagneshbhai Vitthalbhi ", :last_name => "Sanzhani", :email_id => "prem_tatasky@rediffmail.us", :prefix => "Mrs.")
    Member.create(:mobile_phone => "9437649875", :first_name => "Harihar Nath ", :last_name => "KADAM", :email_id => "hariharnathv@transcyber.org", :prefix => "Ms.")
    Member.create(:mobile_phone => "9437549875", :first_name => "Rajveevan", :last_name => "Puthanveettin", :email_id => "KADAM@chsdesk.net", :prefix => "Mrs.")
    Member.create(:mobile_phone => "9437249873", :first_name => "Pramod Mukundrao ", :last_name => "Alkutkar", :email_id => "rpveetil@hotmail.co", :prefix => "Mr.")
    Member.create(:mobile_phone => "9437149874", :first_name => "JAYSHREE", :last_name => "Mangala", :email_id => "ideshcompaq2005@yahoo.co.in", :prefix => "Mr.")
    Member.create(:mobile_phone => "9437359877", :first_name => "Navneet", :last_name => "Singh", :email_id => "arumesh@yahoo.com", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9437346878", :first_name => "YUSUF ", :last_name => "Kamble", :email_id => "YUSUFk@transcyber.org", :prefix => "Mr.")
    Member.create(:mobile_phone => "9437343879", :first_name => "Keshav Singh ", :last_name => "Sachdev", :email_id => "laxmi@biz.hfclconnect.com", :prefix => "Shri")
    Member.create(:mobile_phone => "9437344870", :first_name => "Deepak", :last_name => "Malhotra", :email_id => "vikasbhakr@yahoo.com", :prefix => "Shri")
    Member.create(:mobile_phone => "9437346885", :first_name => "Brijesh", :last_name => "NAIK", :email_id => "tummala.kiran@idea.rediffmail.org", :prefix => "Dr.")
    Member.create(:mobile_phone => "9243707178", :first_name => "Tanuja", :last_name => "Shah", :email_id => "SOMAJI@ahem.be", :prefix => "Dr.")
    Member.create(:mobile_phone => "9843707178", :first_name => "SONALI", :last_name => "Shah", :email_id => "willd@ahem.be", :prefix => "Mr.")
    Member.create(:mobile_phone => "9543707178", :first_name => "DEVANAND", :last_name => "Shah", :email_id => "ASHRAF@ahem.be", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9343707178", :first_name => "KANNA", :last_name => "Shah", :email_id => "onyewuo@ahem.be", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9443707178", :first_name => "Gagan", :last_name => "Shah", :email_id => "sarrm@ahem.be", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9911736445", :first_name => "SUYASH", :last_name => "SINGH", :email_id => "SINGHl@ahem.be", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9811736445", :first_name => "RITESH", :last_name => "Witsel", :email_id => "witsela@ahem.be", :prefix => "Mr.")
    Member.create(:mobile_phone => "9711736445", :first_name => "ACHARYA", :last_name => "Defour", :email_id => "defours@hotmail.be", :prefix => "Mr.")
    Member.create(:mobile_phone => "9611736445", :first_name => "Sushil", :last_name => "Patel", :email_id => "AVLANIux@hotmail.be", :prefix => "Mr.")
    Member.create(:mobile_phone => "9111736445", :first_name => "PARTHIV", :last_name => "GADA", :email_id => "jova@hotmail.be", :prefix => "Ms.")
    Member.create(:mobile_phone => "9711736445", :first_name => "PALAK", :last_name => "De Camargo", :email_id => "decamar@hotmail.be", :prefix => "Ms.")
    Member.create(:mobile_phone => "9437049875", :first_name => "Dieumerci", :last_name => "GADA", :email_id => "mbokani@hotmail.be", :prefix => "Ms.")
    Member.create(:mobile_phone => "9837849875", :first_name => "NAGESH", :last_name => "Ghosh", :email_id => "nicaise@hotmail.be", :prefix => "Mr.")
    Member.create(:mobile_phone => "9937849875", :first_name => "Sinan", :last_name => "Ghosh", :email_id => "NIKAM@hotmail.be", :prefix => "Ms.")
    Member.create(:mobile_phone => "9537849875", :first_name => "Mhotmailndra", :last_name => "DAS", :email_id => "Mhotmailndrab@hotmail.be", :prefix => "Ms.")
    Member.create(:mobile_phone => "9637849875", :first_name => "MAMTA", :last_name => "DAS", :email_id => "NAIK@hotmail.com", :prefix => "Ms.")
    Member.create(:mobile_phone => "9467849875", :first_name => "Jitendra", :last_name => "Sunderaraj", :email_id => "carce@hotmail.be", :prefix => "Mr.")
    Member.create(:mobile_phone => "9487849875", :first_name => "JAYNARAYAN", :last_name => "Mangala", :email_id => "manga@hotmail.be", :prefix => "Mr.")
    Member.create(:mobile_phone => "9439849875", :first_name => "KIRAN", :last_name => "PUROHIT", :email_id => "miku@hotmail.be", :prefix => "Shri")
    Member.create(:mobile_phone => "9432849875", :first_name => "DSOUZA", :last_name => "PATIL", :email_id => "maestro@hotmail.be", :prefix => "Mr.")
    Member.create(:mobile_phone => "9437049875", :first_name => "Valluuripalli", :last_name => "Patel", :email_id => "bolo@hotmail.be", :prefix => "Mr.")
    Member.create(:mobile_phone => "9437249875", :first_name => "Joaquim", :last_name => "Patel", :email_id => "vishal.vashis@rediffmail.us", :prefix => "Mr.")
    Member.create(:mobile_phone => "9437866875", :first_name => "CHANDRESH", :last_name => "AMBANI", :email_id => "pf@hotmail.be", :prefix => "Ms.")
    Member.create(:mobile_phone => "9437822875", :first_name => "Tarique", :last_name => "Khan", :email_id => "vmalhotra@rmexports.us", :prefix => "Ms.")
    Member.create(:mobile_phone => "9437449875", :first_name => "Jagneshbhai Vitthalbhi ", :last_name => "Sanzhani", :email_id => "premium_tatasy@rediffmail.org", :prefix => "Mrs.")
    Member.create(:mobile_phone => "9437649875", :first_name => "Harihar Nath ", :last_name => "KADAM", :email_id => "hariharnathv@gmail.in", :prefix => "Ms.")
    Member.create(:mobile_phone => "9437549875", :first_name => "Rajveevan  ", :last_name => "MISHARA", :email_id => "NAIK@hotmail.in", :prefix => "Mrs.")
    Member.create(:mobile_phone => "9437249873", :first_name => "Pramod Mukundrao ", :last_name => "Alkutkar", :email_id => "rpveetil@hotmail.com", :prefix => "Mr.")
    Member.create(:mobile_phone => "9437149874", :first_name => "JAYDEEP", :last_name => "Mangala", :email_id => "hideshcompaq200@yahoo.co.in", :prefix => "Mr.")
    Member.create(:mobile_phone => "9437359877", :first_name => "Navneet  ", :last_name => "Singh", :email_id => "arumeshnet@yahoo.com", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9437346878", :first_name => "YOGRAJ Yeshwant ", :last_name => "Kamble", :email_id => "YOGRAJk@gmail.in", :prefix => "Mr.")
    Member.create(:mobile_phone => "9437343879", :first_name => "Keshav Chander Singh ", :last_name => "Sachdev", :email_id => "mahal@biz.hfclconnect.com", :prefix => "Shri")
    Member.create(:mobile_phone => "9437344870", :first_name => "Deepak  ", :last_name => "Malhotra", :email_id => "vikasbhak@yahoo.com", :prefix => "Shri")
    Member.create(:mobile_phone => "9437346885", :first_name => "Brijesh  ", :last_name => "NAIK", :email_id => "tummala.kiran@idea.yahoo.com", :prefix => "Dr.")
    Member.create(:mobile_phone => "9243707178", :first_name => "Tanuja", :last_name => "Shah", :email_id => "hotmail@hotmail.be", :prefix => "Dr.")
    Member.create(:mobile_phone => "9843707178", :first_name => "SMITA", :last_name => "Shah", :email_id => "willd@hotmail.be", :prefix => "Mr.")
    Member.create(:mobile_phone => "9543707178", :first_name => "RAMESH", :last_name => "Shah", :email_id => "ASHRAF@hotmail.be", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9343707178", :first_name => "ANITA", :last_name => "Shah", :email_id => "onyewuo@chsdesk.net", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9443707178", :first_name => "Gagan", :last_name => "Shah", :email_id => "sarrm@gmail.be", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9911736445", :first_name => "SUWARNA", :last_name => "SINGH", :email_id => "SINGHl@gmail.be", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9811736445", :first_name => "SURESH", :last_name => "Witsel", :email_id => "witsela@gmail.be", :prefix => "Mr.")
    Member.create(:mobile_phone => "9711736445", :first_name => "ADESH", :last_name => "Defour", :email_id => "defours@gmail.be", :prefix => "Mr.")
    Member.create(:mobile_phone => "9611736445", :first_name => "SANDESH", :last_name => "Patel", :email_id => "GUPTA@gmail.be", :prefix => "Mr.")
    Member.create(:mobile_phone => "9111736445", :first_name => "REENA", :last_name => "GADA", :email_id => "jova@gmail.be", :prefix => "Ms.")
    Member.create(:mobile_phone => "9711736445", :first_name => "BALWANT", :last_name => "De Camargo", :email_id => "decamar@gmail.be", :prefix => "Ms.")
    Member.create(:mobile_phone => "9437049875", :first_name => "Dieumerci", :last_name => "MODI ", :email_id => "mbokani@gmail.be", :prefix => "Ms.")
    Member.create(:mobile_phone => "9837849875", :first_name => "KESHUDAS", :last_name => "Ghosh", :email_id => "nicaise@gmail.be", :prefix => "Mr.")
    Member.create(:mobile_phone => "9937849875", :first_name => "Sinan", :last_name => "Ghosh", :email_id => "NIKAM@gmail.be", :prefix => "Ms.")
    Member.create(:mobile_phone => "9537849875", :first_name => "YOGITA", :last_name => "Netravalkar", :email_id => "YOGITAb@gmail.be", :prefix => "Ms.")
    Member.create(:mobile_phone => "9637849875", :first_name => "KRIRTKUMAR", :last_name => "KOTHARI", :email_id => "DEDHIA@gmail.be", :prefix => "Ms.")
    Member.create(:mobile_phone => "9467849875", :first_name => "Jitendra", :last_name => "KOTHARI", :email_id => "carce@gmail.be", :prefix => "Mr.")
    Member.create(:mobile_phone => "9487849875", :first_name => "JAYANT", :last_name => "Mangala", :email_id => "manga@gmail.be", :prefix => "Mr.")
    Member.create(:mobile_phone => "9439849875", :first_name => "KHALID", :last_name => "PUROHIT", :email_id => "miku@gmail.be", :prefix => "Shri")
    Member.create(:mobile_phone => "9432849875", :first_name => "WENDY", :last_name => "PAREKH", :email_id => "maestro@gmail.be", :prefix => "Mr.")
    Member.create(:mobile_phone => "9437049875", :first_name => "Valluuripalli", :last_name => "Patel", :email_id => "bolo@gmail.be", :prefix => "Mr.")
    Member.create(:mobile_phone => "9437249875", :first_name => "Joaquim", :last_name => "Patel", :email_id => "vishal.vashi@rediffmail.com", :prefix => "Mr.")
    Member.create(:mobile_phone => "9437866875", :first_name => "ARVIND", :last_name => "AMBANI", :email_id => "af@gmail.be", :prefix => "Ms.")
    Member.create(:mobile_phone => "9437822875", :first_name => "Tarique", :last_name => "Khan", :email_id => "vmalhotra@rmexports.aus", :prefix => "Ms.")
    Member.create(:mobile_phone => "9437449875", :first_name => "Jagneshbhai Vitthalbhi ", :last_name => "Sanzhani", :email_id => "premium_tatk@rediffmail.org", :prefix => "Mrs.")
    Member.create(:mobile_phone => "9437649875", :first_name => "Harihar Nath ", :last_name => "KADAM", :email_id => "hariharnathv@gmail.net", :prefix => "Ms.")
    Member.create(:mobile_phone => "9437549875", :first_name => "Rajveevan  ", :last_name => "MISHARA", :email_id => "DEDHIA@chsdesk.org", :prefix => "Mrs.")
    Member.create(:mobile_phone => "9437249873", :first_name => "Pramod Mukundrao ", :last_name => "Alkutkar", :email_id => "rpvetil@hotmail.com", :prefix => "Mr.")
    Member.create(:mobile_phone => "9437149874", :first_name => "JAMSHED", :last_name => "Mangala", :email_id => "hideshcompaq005@yahoo.co.in", :prefix => "Mr.")
    Member.create(:mobile_phone => "9437359877", :first_name => "Navneet  ", :last_name => "Singh", :email_id => "umeshnetra@yahoo.com", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9437346878", :first_name => "YOGINI Yeshwant ", :last_name => "Kamble", :email_id => "YOGINIk@gmail.net", :prefix => "Mr.")
    Member.create(:mobile_phone => "9437343879", :first_name => "Keshav Chander Singh ", :last_name => "Sachdev", :email_id => "mahalaxmi@hfclconnect.com", :prefix => "Shri")
    Member.create(:mobile_phone => "9437344870", :first_name => "Deepak  ", :last_name => "Malhotra", :email_id => "vikasbha@yahoo.com", :prefix => "Shri")
    Member.create(:mobile_phone => "9437346885", :first_name => "Brijesh  ", :last_name => "NAIK", :email_id => "tummala.kiran@idea.gmail.net", :prefix => "Dr.")
    Member.create(:mobile_phone => "9243707178", :first_name => "BALLAMA", :last_name => "Shah", :email_id => "SOMAJI@gmail.com", :prefix => "Dr.")
    Member.create(:mobile_phone => "9843707178", :first_name => "SIDDHESH", :last_name => "Shah", :email_id => "silld@gmail.com", :prefix => "Mr.")
    Member.create(:mobile_phone => "9543707178", :first_name => "BHARATI", :last_name => "Shah", :email_id => "ASHRAF@gmail.com", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9343707178", :first_name => "YOGESH", :last_name => "Shah", :email_id => "onyewuo@gmail.com", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9443707178", :first_name => "Gagan", :last_name => "Shah", :email_id => "sarrm@gmail.com", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9911736445", :first_name => "SANJEEV", :last_name => "SINGH", :email_id => "RATHODl@gmail.com", :prefix => "Shrimati")
    Member.create(:mobile_phone => "9811736445", :first_name => "VENKATESH", :last_name => "Witsel", :email_id => "witsela@gmail.com", :prefix => "Mr.")
    Member.create(:mobile_phone => "9711736445", :first_name => "ADHIKARY", :last_name => "Defour", :email_id => "BHASWANT@gmail.com", :prefix => "Mr.")
    Member.create(:mobile_phone => "9611736445", :first_name => "Sohanlal", :last_name => "Patel", :email_id => "MEHTA@gmail.com", :prefix => "Mr.")
    Member.create(:mobile_phone => "9111736445", :first_name => "REKHA", :last_name => "MODI ", :email_id => "jova@gmail.com", :prefix => "Ms.")
    Member.create(:mobile_phone => "9711736445", :first_name => "OMAR", :last_name => "De Camargo", :email_id => "decamar@gmail.com", :prefix => "Ms.")
    Member.create(:mobile_phone => "9437049875", :first_name => "Dieumerci", :last_name => "MODI ", :email_id => "mbokani@gmail.com", :prefix => "Ms.")
    Member.create(:mobile_phone => "9837849875", :first_name => "MUKESH", :last_name => "Ghosh", :email_id => "nicaise@gmail.com", :prefix => "Mr.")
    Member.create(:mobile_phone => "9937849875", :first_name => "Sinan", :last_name => "Ghosh", :email_id => "Sinan@gmail.com", :prefix => "Ms.")
    Member.create(:mobile_phone => "9537849875", :first_name => "YOGESH", :last_name => "KOTHARI", :email_id => "YOGESHb@gmail.com", :prefix => "Ms.")
    Member.create(:mobile_phone => "9637849875", :first_name => "PRAKASH", :last_name => "KOTHARI", :email_id => "DAS@gmail.com", :prefix => "Ms.")
    Member.create(:mobile_phone => "9467849875", :first_name => "Jitendra", :last_name => "CHAOUDHARI", :email_id => "carce@gmail.com", :prefix => "Mr.")
    Member.create(:mobile_phone => "9487849875", :first_name => "JAIKISHAN", :last_name => "Mangala", :email_id => "manga@gmail.com", :prefix => "Mr.")
    Member.create(:mobile_phone => "9439849875", :first_name => "KETAKI", :last_name => "PUROHIT", :email_id => "miku@gmail.com", :prefix => "Shri")
  
    add_index :members, :email_id

  end
end
