class CreateUnits < ActiveRecord::Migration
  def change
    create_table :units do |t|
      t.string :unit_number,        :limit => 20,  :null => false
      t.string :wing_name,          :limit => 10,  :null => false
      t.string :building_name,      :limit => 10,  :null => false, :default => '1'
      t.string :floor_name,         :limit => 10,  :null => false
      t.decimal :noc_charges,       :precision => 7, :scale => 2, :default => 0
      t.decimal :parking_charges,   :precision => 7, :scale => 2, :default => 0
      t.decimal :property_tax,      :precision => 8, :scale => 2, :default => 0
      t.decimal :maintenance_charge, :precision => 8, :scale => 2, :default => 0
      t.decimal :sinking_fund,      :precision => 8, :scale => 2, :default => 0
      t.decimal :repair_fund,       :precision => 8, :scale => 2, :default => 0
      t.decimal :service_tax,       :precision => 8, :scale => 2, :default => 0
      t.decimal :discount,          :precision => 8, :scale => 2, :default => 0
      t.decimal :other_charge,      :precision => 8, :scale => 2, :default => 0
      t.decimal :bill_amount,       :precision => 9, :scale => 2, :default => 0
      t.string :other_detail 
      t.boolean :assigned,          :default => false       
      t.integer :unit_type_id,      :default => '1'
      t.integer :society_id,        :default => '1'
      t.integer :bill_setup_id,     :default => '1'
      t.integer :sold_status_id,        :default => '1'
      t.integer :Occupation_status_id,  :default => '1'
      t.integer :maintenance_by_id,     :default => '1'

      t.timestamps
    end
     
      Unit.create(:unit_number => '1702',:wing_name => 'A',:building_name => '1',:floor_name => '17',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1701',:wing_name => 'A',:building_name => '1',:floor_name => '17',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1602',:wing_name => 'A',:building_name => '1',:floor_name => '16',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1601',:wing_name => 'A',:building_name => '1',:floor_name => '16',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1502',:wing_name => 'A',:building_name => '1',:floor_name => '15',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1501',:wing_name => 'A',:building_name => '1',:floor_name => '15',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1402',:wing_name => 'A',:building_name => '1',:floor_name => '14',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1401',:wing_name => 'A',:building_name => '1',:floor_name => '14',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1302',:wing_name => 'A',:building_name => '1',:floor_name => '13',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1301',:wing_name => 'A',:building_name => '1',:floor_name => '13',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1202',:wing_name => 'A',:building_name => '1',:floor_name => '12',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1201',:wing_name => 'A',:building_name => '1',:floor_name => '12',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1102',:wing_name => 'A',:building_name => '1',:floor_name => '11',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1101',:wing_name => 'A',:building_name => '1',:floor_name => '11',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1002',:wing_name => 'A',:building_name => '1',:floor_name => '10',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1001',:wing_name => 'A',:building_name => '1',:floor_name => '10',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1802',:wing_name => 'A',:building_name => '1',:floor_name => '18',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '1801',:wing_name => 'A',:building_name => '1',:floor_name => '18',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '1902',:wing_name => 'A',:building_name => '1',:floor_name => '19',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '1901',:wing_name => 'A',:building_name => '1',:floor_name => '19',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '2002',:wing_name => 'A',:building_name => '1',:floor_name => '20',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '2001',:wing_name => 'A',:building_name => '1',:floor_name => '20',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '101',:wing_name => 'A',:building_name => '1',:floor_name => '1',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '102',:wing_name => 'A',:building_name => '1',:floor_name => '1',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '201',:wing_name => 'A',:building_name => '1',:floor_name => '2',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '202',:wing_name => 'A',:building_name => '1',:floor_name => '2',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '301',:wing_name => 'A',:building_name => '1',:floor_name => '3',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '302',:wing_name => 'A',:building_name => '1',:floor_name => '3',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '401',:wing_name => 'A',:building_name => '1',:floor_name => '4',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '402',:wing_name => 'A',:building_name => '1',:floor_name => '4',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '403',:wing_name => 'A',:building_name => '1',:floor_name => '4',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '404',:wing_name => 'A',:building_name => '1',:floor_name => '4',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '405',:wing_name => 'A',:building_name => '1',:floor_name => '4',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '406',:wing_name => 'A',:building_name => '1',:floor_name => '4',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '501',:wing_name => 'A',:building_name => '1',:floor_name => '5',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '502',:wing_name => 'A',:building_name => '1',:floor_name => '5',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '503',:wing_name => 'A',:building_name => '1',:floor_name => '5',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '504',:wing_name => 'A',:building_name => '1',:floor_name => '5',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '505',:wing_name => 'A',:building_name => '1',:floor_name => '5',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '506',:wing_name => 'A',:building_name => '1',:floor_name => '5',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '601',:wing_name => 'A',:building_name => '1',:floor_name => '6',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '602',:wing_name => 'A',:building_name => '1',:floor_name => '6',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '603',:wing_name => 'A',:building_name => '1',:floor_name => '6',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '604',:wing_name => 'A',:building_name => '1',:floor_name => '6',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '605',:wing_name => 'A',:building_name => '1',:floor_name => '6',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '606',:wing_name => 'A',:building_name => '1',:floor_name => '6',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '701',:wing_name => 'A',:building_name => '1',:floor_name => '7',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '702',:wing_name => 'A',:building_name => '1',:floor_name => '7',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '703',:wing_name => 'A',:building_name => '1',:floor_name => '7',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '704',:wing_name => 'A',:building_name => '1',:floor_name => '7',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '705',:wing_name => 'A',:building_name => '1',:floor_name => '7',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '706',:wing_name => 'A',:building_name => '1',:floor_name => '7',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '801',:wing_name => 'A',:building_name => '1',:floor_name => '8',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '802',:wing_name => 'A',:building_name => '1',:floor_name => '8',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '803',:wing_name => 'A',:building_name => '1',:floor_name => '8',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '804',:wing_name => 'A',:building_name => '1',:floor_name => '8',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '805',:wing_name => 'A',:building_name => '1',:floor_name => '8',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '806',:wing_name => 'A',:building_name => '1',:floor_name => '8',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '901',:wing_name => 'A',:building_name => '1',:floor_name => '9',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '902',:wing_name => 'A',:building_name => '1',:floor_name => '9',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '903',:wing_name => 'A',:building_name => '1',:floor_name => '9',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '904',:wing_name => 'A',:building_name => '1',:floor_name => '9',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '905',:wing_name => 'A',:building_name => '1',:floor_name => '9',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '906',:wing_name => 'A',:building_name => '1',:floor_name => '9',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1703',:wing_name => 'B',:building_name => '1',:floor_name => '17',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1704',:wing_name => 'B',:building_name => '1',:floor_name => '17',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1702',:wing_name => 'B',:building_name => '1',:floor_name => '17',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1701',:wing_name => 'B',:building_name => '1',:floor_name => '17',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1705',:wing_name => 'B',:building_name => '1',:floor_name => '17',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1706',:wing_name => 'B',:building_name => '1',:floor_name => '17',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1603',:wing_name => 'B',:building_name => '1',:floor_name => '16',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1604',:wing_name => 'B',:building_name => '1',:floor_name => '16',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1602',:wing_name => 'B',:building_name => '1',:floor_name => '16',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1601',:wing_name => 'B',:building_name => '1',:floor_name => '16',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1605',:wing_name => 'B',:building_name => '1',:floor_name => '16',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1606',:wing_name => 'B',:building_name => '1',:floor_name => '16',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1503',:wing_name => 'B',:building_name => '1',:floor_name => '15',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1504',:wing_name => 'B',:building_name => '1',:floor_name => '15',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1502',:wing_name => 'B',:building_name => '1',:floor_name => '15',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1501',:wing_name => 'B',:building_name => '1',:floor_name => '15',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1505',:wing_name => 'B',:building_name => '1',:floor_name => '15',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1506',:wing_name => 'B',:building_name => '1',:floor_name => '15',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1403',:wing_name => 'B',:building_name => '1',:floor_name => '14',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1404',:wing_name => 'B',:building_name => '1',:floor_name => '14',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1402',:wing_name => 'B',:building_name => '1',:floor_name => '14',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1401',:wing_name => 'B',:building_name => '1',:floor_name => '14',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1405',:wing_name => 'B',:building_name => '1',:floor_name => '14',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1406',:wing_name => 'B',:building_name => '1',:floor_name => '14',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1303',:wing_name => 'B',:building_name => '1',:floor_name => '13',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1304',:wing_name => 'B',:building_name => '1',:floor_name => '13',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1302',:wing_name => 'B',:building_name => '1',:floor_name => '13',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1301',:wing_name => 'B',:building_name => '1',:floor_name => '13',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1305',:wing_name => 'B',:building_name => '1',:floor_name => '13',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1306',:wing_name => 'B',:building_name => '1',:floor_name => '13',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1203',:wing_name => 'B',:building_name => '1',:floor_name => '12',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1204',:wing_name => 'B',:building_name => '1',:floor_name => '12',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1202',:wing_name => 'B',:building_name => '1',:floor_name => '12',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1201',:wing_name => 'B',:building_name => '1',:floor_name => '12',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1205',:wing_name => 'B',:building_name => '1',:floor_name => '12',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1206',:wing_name => 'B',:building_name => '1',:floor_name => '12',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1103',:wing_name => 'B',:building_name => '1',:floor_name => '11',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1104',:wing_name => 'B',:building_name => '1',:floor_name => '11',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1102',:wing_name => 'B',:building_name => '1',:floor_name => '11',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1101',:wing_name => 'B',:building_name => '1',:floor_name => '11',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1105',:wing_name => 'B',:building_name => '1',:floor_name => '11',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1106',:wing_name => 'B',:building_name => '1',:floor_name => '11',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1003',:wing_name => 'B',:building_name => '1',:floor_name => '10',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1004',:wing_name => 'B',:building_name => '1',:floor_name => '10',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1002',:wing_name => 'B',:building_name => '1',:floor_name => '10',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1001',:wing_name => 'B',:building_name => '1',:floor_name => '10',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1005',:wing_name => 'B',:building_name => '1',:floor_name => '10',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1006',:wing_name => 'B',:building_name => '1',:floor_name => '10',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1803',:wing_name => 'B',:building_name => '1',:floor_name => '18',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1804',:wing_name => 'B',:building_name => '1',:floor_name => '18',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1802',:wing_name => 'B',:building_name => '1',:floor_name => '18',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1801',:wing_name => 'B',:building_name => '1',:floor_name => '18',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1805',:wing_name => 'B',:building_name => '1',:floor_name => '18',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1806',:wing_name => 'B',:building_name => '1',:floor_name => '18',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1903',:wing_name => 'B',:building_name => '1',:floor_name => '19',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1904',:wing_name => 'B',:building_name => '1',:floor_name => '19',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1902',:wing_name => 'B',:building_name => '1',:floor_name => '19',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1901',:wing_name => 'B',:building_name => '1',:floor_name => '19',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1905',:wing_name => 'B',:building_name => '1',:floor_name => '19',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1906',:wing_name => 'B',:building_name => '1',:floor_name => '19',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '2003',:wing_name => 'B',:building_name => '1',:floor_name => '20',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '2004',:wing_name => 'B',:building_name => '1',:floor_name => '20',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '2005',:wing_name => 'B',:building_name => '1',:floor_name => '20',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '2006',:wing_name => 'B',:building_name => '1',:floor_name => '20',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '2002',:wing_name => 'B',:building_name => '1',:floor_name => '20',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '2001',:wing_name => 'B',:building_name => '1',:floor_name => '20',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '101',:wing_name => 'B',:building_name => '1',:floor_name => '1',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '102',:wing_name => 'B',:building_name => '1',:floor_name => '1',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '103',:wing_name => 'B',:building_name => '1',:floor_name => '1',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '104',:wing_name => 'B',:building_name => '1',:floor_name => '1',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '105',:wing_name => 'B',:building_name => '1',:floor_name => '1',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '106',:wing_name => 'B',:building_name => '1',:floor_name => '1',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '201',:wing_name => 'B',:building_name => '1',:floor_name => '2',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '202',:wing_name => 'B',:building_name => '1',:floor_name => '2',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '203',:wing_name => 'B',:building_name => '1',:floor_name => '2',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '204',:wing_name => 'B',:building_name => '1',:floor_name => '2',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '205',:wing_name => 'B',:building_name => '1',:floor_name => '2',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '206',:wing_name => 'B',:building_name => '1',:floor_name => '2',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '301',:wing_name => 'B',:building_name => '1',:floor_name => '3',:unit_type_id => 9,:society_id => 1)


  end
end
